//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class bancos_cuentas
    {
        public int id { get; set; }
        public Nullable<int> id_banco { get; set; }
        public Nullable<int> id_tipo_cuenta { get; set; }
        public string nro_cuenta { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual bancos bancos { get; set; }
        public virtual bancos_tipos_cuentas bancos_tipos_cuentas { get; set; }
        public virtual monedas monedas { get; set; }
    }
}
