//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajas_ajustes
    {
        public int id { get; set; }
        public Nullable<int> id_caja { get; set; }
        public Nullable<int> id_caja_apertura { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> faltante { get; set; }
        public Nullable<decimal> monto_ajuste { get; set; }
        public string justificacion { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual cajas cajas { get; set; }
        public virtual cajas_aperturas cajas_aperturas { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
