//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajas_arqueos_ventas
    {
        public int id { get; set; }
        public Nullable<int> id_caja_arqueo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> total_neto { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public string nro_factura { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual cajas_arqueos cajas_arqueos { get; set; }
    }
}
