//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajas_composiciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cajas_composiciones()
        {
            this.cajas_composiciones_detalles = new HashSet<cajas_composiciones_detalles>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_caja { get; set; }
        public Nullable<int> id_caja_apertura { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> total_billete { get; set; }
        public Nullable<decimal> total_moneda { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual cajas cajas { get; set; }
        public virtual cajas_aperturas cajas_aperturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_composiciones_detalles> cajas_composiciones_detalles { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
