//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajas_arqueos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cajas_arqueos()
        {
            this.cajas_arqueos_ajustes = new HashSet<cajas_arqueos_ajustes>();
            this.cajas_arqueos_composiciones = new HashSet<cajas_arqueos_composiciones>();
            this.cajas_arqueos_detalles = new HashSet<cajas_arqueos_detalles>();
            this.cajas_arqueos_ventas = new HashSet<cajas_arqueos_ventas>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<int> id_caja_apertura { get; set; }
        public Nullable<decimal> total_ingreso { get; set; }
        public Nullable<decimal> total_egreso { get; set; }
        public Nullable<decimal> total_composicion { get; set; }
        public Nullable<decimal> saldo_efectivo { get; set; }
        public Nullable<decimal> saldo_caja { get; set; }
        public Nullable<decimal> faltante { get; set; }
        public Nullable<decimal> sobrante { get; set; }
        public Nullable<decimal> total_ajuste_faltante { get; set; }
        public Nullable<decimal> total_ajuste_sobrante { get; set; }
        public Nullable<decimal> diferencia { get; set; }
        public string observacion { get; set; }
        public Nullable<bool> arqueo_final { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual cajas_aperturas cajas_aperturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_arqueos_ajustes> cajas_arqueos_ajustes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_arqueos_composiciones> cajas_arqueos_composiciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_arqueos_detalles> cajas_arqueos_detalles { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_arqueos_ventas> cajas_arqueos_ventas { get; set; }
    }
}
