//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cajas()
        {
            this.cajas_ajustes = new HashSet<cajas_ajustes>();
            this.cajas_aperturas = new HashSet<cajas_aperturas>();
            this.cajas_composiciones = new HashSet<cajas_composiciones>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string denominacion { get; set; }
        public Nullable<bool> abierto { get; set; }
        public Nullable<decimal> saldo_caja { get; set; }
        public Nullable<decimal> saldo_efectivo { get; set; }
        public Nullable<decimal> sobrante { get; set; }
        public Nullable<decimal> faltante { get; set; }
        public Nullable<bool> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_ajustes> cajas_ajustes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_aperturas> cajas_aperturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajas_composiciones> cajas_composiciones { get; set; }
        public virtual monedas monedas { get; set; }
        public virtual sucursales sucursales { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
