//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajas_arqueos_detalles
    {
        public int id { get; set; }
        public Nullable<int> id_caja_arqueo { get; set; }
        public string concepto { get; set; }
        public Nullable<decimal> ingreso { get; set; }
        public Nullable<decimal> egreso { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual cajas_arqueos cajas_arqueos { get; set; }
    }
}
