//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajas_composiciones_detalles
    {
        public int id { get; set; }
        public Nullable<int> id_caja_composicion { get; set; }
        public Nullable<int> id_denominacion_moneda { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual cajas_composiciones cajas_composiciones { get; set; }
        public virtual denominaciones_monedas denominaciones_monedas { get; set; }
    }
}
