//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clientes()
        {
            this.clientes_contactos = new HashSet<clientes_contactos>();
            this.reservas_habitaciones = new HashSet<reservas_habitaciones>();
            this.consumisiones = new HashSet<consumisiones>();
            this.cuentas_clientes = new HashSet<cuentas_clientes>();
            this.facturaciones = new HashSet<facturaciones>();
            this.facturaciones_temporales = new HashSet<facturaciones_temporales>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public string nro_documento { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string razon_social { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<int> id_ciudad { get; set; }
        public Nullable<int> id_barrio { get; set; }
        public string direccion { get; set; }
        public string email_principal { get; set; }
        public string nro_telefono_principal { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<int> id_profesion { get; set; }
        public Nullable<int> id_estado_civil { get; set; }
        public string genero { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual barrios barrios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientes_contactos> clientes_contactos { get; set; }
        public virtual departamentos departamentos { get; set; }
        public virtual estados_civiles estados_civiles { get; set; }
        public virtual paises paises { get; set; }
        public virtual profesiones profesiones { get; set; }
        public virtual tipos_documentos tipos_documentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservas_habitaciones> reservas_habitaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumisiones> consumisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentas_clientes> cuentas_clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaciones> facturaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaciones_temporales> facturaciones_temporales { get; set; }
    }
}
