//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes_contactos
    {
        public int id { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_tipo_contacto { get; set; }
        public string contacto { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual tipos_contactos tipos_contactos { get; set; }
    }
}
