//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras_productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public compras_productos()
        {
            this.compras_productos_detalles = new HashSet<compras_productos_detalles>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_condicion_compra { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> id_proveedor_sucursal { get; set; }
        public string nro_factura { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> total_neto { get; set; }
        public Nullable<decimal> total_bruto { get; set; }
        public Nullable<decimal> saldo_factura { get; set; }
        public Nullable<decimal> total_gravada_iva { get; set; }
        public string observarcion { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual condiciones_compras_ventas condiciones_compras_ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compras_productos_detalles> compras_productos_detalles { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual proveedores_sucursales proveedores_sucursales { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
