//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumisiones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public consumisiones()
        {
            this.consumisiones_detalles = new HashSet<consumisiones_detalles>();
            this.cargas_cuentas = new HashSet<cargas_cuentas>();
            this.facturaciones = new HashSet<facturaciones>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_mesa { get; set; }
        public Nullable<int> id_mozo { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string ruc_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<bool> consumision_terminado { get; set; }
        public Nullable<decimal> total_consumision { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual clientes clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumisiones_detalles> consumisiones_detalles { get; set; }
        public virtual mesas mesas { get; set; }
        public virtual mozos mozos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cargas_cuentas> cargas_cuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaciones> facturaciones { get; set; }
    }
}
