//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentas_proveedores
    {
        public int id { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> id_proveedor_sucursal { get; set; }
        public Nullable<int> id_compra_producto { get; set; }
        public Nullable<decimal> deuda { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<bool> saldo_modificado { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual proveedores proveedores { get; set; }
        public virtual proveedores_sucursales proveedores_sucursales { get; set; }
    }
}
