//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentas_clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuentas_clientes()
        {
            this.cuentas_clientes_detalles = new HashSet<cuentas_clientes_detalles>();
            this.cuentas_clientes_pagos = new HashSet<cuentas_clientes_pagos>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_reserva { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<decimal> total_pagar { get; set; }
        public Nullable<decimal> saldo_pendiente { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual clientes clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentas_clientes_detalles> cuentas_clientes_detalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentas_clientes_pagos> cuentas_clientes_pagos { get; set; }
        public virtual reservas_habitaciones reservas_habitaciones { get; set; }
    }
}
