//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentas_clientes_detalles
    {
        public int id { get; set; }
        public Nullable<int> id_cuenta_cliente { get; set; }
        public Nullable<int> id_tarifa_detalle { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual cuentas_clientes cuentas_clientes { get; set; }
        public virtual tarifas_detalles tarifas_detalles { get; set; }
    }
}
