//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class denominaciones_monedas
    {
        public int id { get; set; }
        public Nullable<int> id_tipo_denominacion { get; set; }
        public string denominacion { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual denominaciones_monedas_tipos denominaciones_monedas_tipos { get; set; }
        public virtual monedas monedas { get; set; }
    }
}
