//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facturaciones()
        {
            this.facturaciones_detalles = new HashSet<facturaciones_detalles>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_consumicion { get; set; }
        public Nullable<int> id_condicion_venta { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_timbrado { get; set; }
        public Nullable<int> id_timbrado_rango { get; set; }
        public string nro_factura { get; set; }
        public Nullable<int> id_motivo_descuento { get; set; }
        public Nullable<decimal> total_descuento { get; set; }
        public Nullable<decimal> total_neto { get; set; }
        public Nullable<decimal> total_bruto { get; set; }
        public Nullable<decimal> saldo_factura { get; set; }
        public Nullable<bool> saldo_modificado { get; set; }
        public Nullable<bool> anulado { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual condiciones_compras_ventas condiciones_compras_ventas { get; set; }
        public virtual consumisiones consumisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaciones_detalles> facturaciones_detalles { get; set; }
        public virtual motivos_descuentos motivos_descuentos { get; set; }
        public virtual timbrados timbrados { get; set; }
        public virtual timbrados_rangos timbrados_rangos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
