//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public funcionarios()
        {
            this.timbrados_rangos_funcionarios = new HashSet<timbrados_rangos_funcionarios>();
            this.usuarios = new HashSet<usuarios>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public string nro_documento { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> id_area { get; set; }
        public Nullable<int> id_cargo { get; set; }
        public string nro_telefono_principal { get; set; }
        public string direccion { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public Nullable<bool> es_supervisor { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual areas areas { get; set; }
        public virtual cargos cargos { get; set; }
        public virtual sucursales sucursales { get; set; }
        public virtual tipos_documentos tipos_documentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timbrados_rangos_funcionarios> timbrados_rangos_funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
