//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public habitaciones()
        {
            this.tarifas_detalles = new HashSet<tarifas_detalles>();
            this.reservas_habitaciones = new HashSet<reservas_habitaciones>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_tipo_habitacion { get; set; }
        public Nullable<int> id_habitacion_estado { get; set; }
        public string numero { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual habitaciones_estados habitaciones_estados { get; set; }
        public virtual habitaciones_tipos habitaciones_tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarifas_detalles> tarifas_detalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservas_habitaciones> reservas_habitaciones { get; set; }
    }
}
