//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos
    {
        public int id { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<int> id_modulo_operacion { get; set; }
        public Nullable<bool> habilitado { get; set; }
    
        public virtual modulos_operaciones modulos_operaciones { get; set; }
        public virtual perfiles perfiles { get; set; }
    }
}
