//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_lotes_ajustes
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_producto_lote { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string observacion { get; set; }
        public Nullable<bool> ingreso_lote { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual productos_lotes productos_lotes { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
