//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.compras_productos_detalles = new HashSet<compras_productos_detalles>();
            this.productos_lotes = new HashSet<productos_lotes>();
            this.consumisiones_detalles = new HashSet<consumisiones_detalles>();
            this.cargas_cuentas_detalles = new HashSet<cargas_cuentas_detalles>();
            this.facturaciones_detalles = new HashSet<facturaciones_detalles>();
        }
    
        public int id { get; set; }
        public string nombre_producto { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<int> id_unidad { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<decimal> precio_costo { get; set; }
        public Nullable<decimal> stock { get; set; }
        public Nullable<int> id_tipo_iva { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual categorias categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compras_productos_detalles> compras_productos_detalles { get; set; }
        public virtual marcas marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_lotes> productos_lotes { get; set; }
        public virtual tipos_ivas tipos_ivas { get; set; }
        public virtual unidades unidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumisiones_detalles> consumisiones_detalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cargas_cuentas_detalles> cargas_cuentas_detalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaciones_detalles> facturaciones_detalles { get; set; }
    }
}
