//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservas_habitaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservas_habitaciones()
        {
            this.cuentas_clientes = new HashSet<cuentas_clientes>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<int> id_usuario_apertura { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
        public Nullable<int> id_tipo_habitacion { get; set; }
        public Nullable<int> id_habitacion { get; set; }
        public Nullable<int> id_reserva_estado { get; set; }
        public Nullable<System.DateTime> check_in { get; set; }
        public Nullable<System.DateTime> check_out { get; set; }
        public Nullable<int> cantidad_adultos { get; set; }
        public Nullable<int> cantidad_menores { get; set; }
        public Nullable<int> id_usuario_cierre { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public string nro_documento { get; set; }
        public string nombre_completo { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual habitaciones habitaciones { get; set; }
        public virtual habitaciones_tipos habitaciones_tipos { get; set; }
        public virtual reservas_estados reservas_estados { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentas_clientes> cuentas_clientes { get; set; }
    }
}
