//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sucursales()
        {
            this.funcionarios = new HashSet<funcionarios>();
        }
    
        public int id { get; set; }
        public string nombre_sucursal { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<int> id_ciudad { get; set; }
        public Nullable<int> id_barrio { get; set; }
        public string direccion { get; set; }
        public Nullable<bool> casa_matriz { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual barrios barrios { get; set; }
        public virtual ciudades ciudades { get; set; }
        public virtual departamentos departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<funcionarios> funcionarios { get; set; }
        public virtual paises paises { get; set; }
    }
}
