//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarifas_detalles
    {
        public int id { get; set; }
        public Nullable<int> id_tarifa { get; set; }
        public Nullable<int> id_habitacion { get; set; }
        public Nullable<int> id_servicio_habitacion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual habitaciones habitaciones { get; set; }
        public virtual habitaciones_servicios habitaciones_servicios { get; set; }
        public virtual tarifas tarifas { get; set; }
    }
}
