//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarifas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarifas()
        {
            this.tarifas_detalles = new HashSet<tarifas_detalles>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_tipo_tarifa { get; set; }
        public string nombre_tarifa { get; set; }
        public Nullable<System.DateTime> valido_desde { get; set; }
        public Nullable<System.DateTime> valido_hasta { get; set; }
        public Nullable<bool> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarifas_detalles> tarifas_detalles { get; set; }
        public virtual tarifas_tipos tarifas_tipos { get; set; }
    }
}
