//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class timbrados_rangos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public timbrados_rangos()
        {
            this.timbrados_comprobantes_anulaciones = new HashSet<timbrados_comprobantes_anulaciones>();
            this.timbrados_rangos_funcionarios = new HashSet<timbrados_rangos_funcionarios>();
            this.facturaciones = new HashSet<facturaciones>();
            this.facturaciones_temporales = new HashSet<facturaciones_temporales>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_timbrado_tipo_rango { get; set; }
        public Nullable<int> id_timbrado { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string codigo_sucursal { get; set; }
        public string punto_expedicion { get; set; }
        public Nullable<int> cantidad_ceros { get; set; }
        public Nullable<int> desde { get; set; }
        public Nullable<int> hasta { get; set; }
        public Nullable<int> numeracion_actual { get; set; }
        public Nullable<bool> utilizado { get; set; }
        public Nullable<int> cantidad_usada { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual sucursales sucursales { get; set; }
        public virtual timbrados timbrados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timbrados_comprobantes_anulaciones> timbrados_comprobantes_anulaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timbrados_rangos_funcionarios> timbrados_rangos_funcionarios { get; set; }
        public virtual timbrados_rangos_tipos timbrados_rangos_tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaciones> facturaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaciones_temporales> facturaciones_temporales { get; set; }
    }
}
