//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id { get; set; }
        public Nullable<int> id_funcionario { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string email { get; set; }
        public Nullable<bool> primera_vez { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public string token_recovery { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual funcionarios funcionarios { get; set; }
        public virtual perfiles perfiles { get; set; }
    }
}
