//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesHoteleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.compras_productos = new HashSet<compras_productos>();
            this.productos_lotes_ajustes = new HashSet<productos_lotes_ajustes>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_funcionario { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string email { get; set; }
        public Nullable<bool> primera_vez { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public string token_recovery { get; set; }
        public Nullable<bool> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compras_productos> compras_productos { get; set; }
        public virtual funcionarios funcionarios { get; set; }
        public virtual perfiles perfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_lotes_ajustes> productos_lotes_ajustes { get; set; }
    }
}
